URL_OLD=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
URL=http://localhost/orangehrm/web/index.php/auth/login
browser=CHROME
username_old=Admin
password_old=admin123
username=sabaritesting
password=Sabaritesting@1298
explicitWait=20