status = error
name = Log4j2Properties

# =============== Rolling File Appender ===============
appender.rolling.type = RollingFile
appender.rolling.name = RollingFileAppender

appender.rolling.fileName = logs/OrangeHRM-${date:yyyy-MM-dd_HH-mm-ss}.log
appender.rolling.filePattern = logs/OrangeHRM-${date:yyyy-MM-dd_HH-mm-ss}-%i.log.gz

appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %c{1} - %msg%n

# Size Policy
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 50MB

# Max backup files
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 30

# =============== Root Logger ===============
rootLogger.level = info
rootLogger.appenderRefs = rolling
rootLogger.appenderRef.rolling.ref = RollingFileAppender